### PR TITLE
Assignment4_part1 & part2

### PR DESCRIPTION
**Pull request by yiiinghuang**
Basic Artificial Neural Network

### CODE REVIEW

**Comment by danilnagy** [comment]
Hi Ying, part 1 looks good, how about part 2?

**Comment by yiiinghuang** [comment]
I am still working on part2 and assignment#4. I will try my best to finish them. Sorry for the delay.

**Comment by danilnagy** [comment]
No worries! Just leave me a note here when they're done.

**Comment by yiiinghuang** [comment]
I just finished the second part of Assignment#4. And I will work on the Assignment#5 on this weekend. 😭

**Comment by danilnagy** [comment]
Got it, good job!

**Pull request closed without merging**
